USE [master]
GO

/****** Object:  Database [DiscoveringEF]    Script Date: 10/06/2009 20:42:17 ******/
CREATE DATABASE [DiscoveringEF] ON  PRIMARY 
( NAME = N'DiscoveringEF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DiscoveringEF.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DiscoveringEF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DiscoveringEF_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DiscoveringEF] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DiscoveringEF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DiscoveringEF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DiscoveringEF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DiscoveringEF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DiscoveringEF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DiscoveringEF] SET ARITHABORT OFF 
GO

ALTER DATABASE [DiscoveringEF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DiscoveringEF] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DiscoveringEF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DiscoveringEF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DiscoveringEF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DiscoveringEF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DiscoveringEF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DiscoveringEF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DiscoveringEF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DiscoveringEF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DiscoveringEF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DiscoveringEF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DiscoveringEF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DiscoveringEF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DiscoveringEF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DiscoveringEF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DiscoveringEF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DiscoveringEF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DiscoveringEF] SET  READ_WRITE 
GO

ALTER DATABASE [DiscoveringEF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DiscoveringEF] SET  MULTI_USER 
GO

ALTER DATABASE [DiscoveringEF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DiscoveringEF] SET DB_CHAINING OFF 
GO


